main: me.vrganj.trolldeluxe.TrollDeluxe
name: TrollDeluxe
description: Have fun and troll others!
author: Vrganj
version: ${version}
api-version: 1.13

commands:
  trolldeluxe:
    aliases: [td]
    description: Supports various troll commands.

permissions:
  trolldeluxe.*:
    description: Allows all trolls
    children:
      trolldeluxe.anvil: true
      trolldeluxe.burn: true
      trolldeluxe.cage: true
      trolldeluxe.creeper: true
      trolldeluxe.deathbed: true
      trolldeluxe.demo: true
      trolldeluxe.gmc: true
      trolldeluxe.gui: true
      trolldeluxe.help: true
      trolldeluxe.join: true
      trolldeluxe.keepinventory: true
      trolldeluxe.launch: true
      trolldeluxe.op: true
      trolldeluxe.potato: true
      trolldeluxe.reload: true
      trolldeluxe.say: true
      trolldeluxe.smite: true
      trolldeluxe.starve: true
      trolldeluxe.tnt: true
      trolldeluxe.wolf: true
  trolldeluxe.help:
    default: true
